### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'reacttmpl.js'

### ISSUE THREAD

**Issue by polmolea** [ganarajpr/image2react#2]
[Enter steps to reproduce below:]
1. in an image, click Convert to React

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [image2react](https://github.com/ganarajpr/image2react) package, v0.5.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'reacttmpl.js'

```
At fs.js:97

Error: ENOENT: no such file or directory, open 'reacttmpl.js'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
  at image-editor-view.initialize (/Users/polmolea/.atom/packages/image2react/lib/ImageEditorElement.js:79:42)
  at createView (/Users/polmolea/.atom/packages/image2react/lib/image2react.js:61:50)
  at openURI (/Users/polmolea/.atom/packages/image2react/lib/image2react.js:42:16)
  at Workspace.module.exports.Workspace.openURIInPane (/Users/polmolea/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:446:22)
  at Workspace.module.exports.Workspace.open (/Users/polmolea/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:379:19)
  at IncomingMessage.<anonymous> (/Users/polmolea/.atom/packages/image2react/lib/panel/ImageButtonElement.js:73:26)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```
### Commands

```
     -5:25 core:paste (atom-text-editor.editor.mini.is-focused)
     -5:08.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:43.2.0 application:add-project-folder (atom-text-editor.editor.is-focused)
  2x -1:57.7.0 image-view:zoom-out (div.image-view)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
image2react, v0.5.2

# Dev
No dev packages
```

**Comment by ganarajpr** [comment]
Hi Andrei,

Thank you for pointing this out. I have now corrected the issue. Please let me know if this still persists.
